### ISSUE TITLE
Is there any way to fix font?

### ISSUE THREAD

**Issue by mingil** [dream10201/115Docker#27]
I'm Korean. Is there any way to fix it because it looks like all the writing is broken unless it's in Chinese, like English and Korean? Below is the docker compose I created based on your site

version: "3.8"

services:
  "115":  
    image: docker.io/xiuxiu10201/115:latest  
    container_name: "115" 
    user: "1026:100"  
    volumes:
      - /volume1/docker/115cloud/etc:/etc/115 
      - /volume1/docker/115cloud/downloads:/opt/Downloads  
    environment: 
      - PASSWORD=123456
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - TZ=Asia/Seoul
    network_mode: host 
    restart: on-failure:5

**Comment by dream10201** [comment]
@mingil The latest container has been fixed.

**Comment by mingil** [comment]
I tried the latest version and it still doesn't work. Is it possible to change the docker environment variable from zh_CN.UTF-8 to something else that includes multiple languages, such as English and Korean? 

Thank you for your efforts.

**Comment by dream10201** [comment]
@mingil You need to check the cache and configuration.
![Image](https://github.com/user-attachments/assets/05d4179c-868b-490d-942b-28a15e2b4cc7)

![Image](https://github.com/user-attachments/assets/baed0f8e-cf47-4717-936b-b526d98b9539)

**Comment by mingil** [comment]
what do you mean chek cache and configuration?
naver.com is korean site and there is no intact font of korean..
I will attach screen shots of naver.com website and my 115 docker
environment variables.
 i am noob for docker sorry...

2025년 2월 24일 (월) 오후 2:41, dream10201 ***@***.***>님이 작성:

**Comment by mingil** [comment]
screen shot

2025년 2월 24일 (월) 오후 2:48, 김민길 ***@***.***>님이 작성:

**Comment by mingil** [comment]
I solved!

i changed environment value to korean

thx!

2025년 2월 24일 (월) 오후 2:48, 김민길 ***@***.***>님이 작성:
